@startuml

!theme bluegray

skinparam componentStyle uml2
skinparam backgroundColor transparent

title **Authentication**

participant "datasync" as datasync << module >>
participant "//GeoNature//" as gn

activate datasync

group Check for login
    datasync -> datasync : set login and password
    datasync -> gn ++ : <font color="goldenrod">**POST**</font> ""/api/auth/login""
     note left
        <code>
        {
            "login": <user login>,
            "password": <user password>,
            "id_application": <sync.gn_application_id from settings>
        }
        </code>
    end note
    gn -> datasync -- : <font color=green">**200**</font>: ""AuthLogin""
    note left
        **""AuthLogin"":**
        </code>
        {
            "user": {
                "id_application": <number>,
                "id_organisme": <number>,
                "identifiant": <user login>
            },
            "expires": <Date>
        }
        </code>
    end note

    datasync -> datasync : set cookie
end

@enduml