= Synchronization workflow

== Update local database from GeoNature

[plantuml, images/sync_data, svg]
....
participant "mobile/sync" as sync << mobile >>
participant "GeoNature" as gn

activate sync

group Fetch common configuration data
  sync -> gn ++ : **GET** : ""/sync""
  gn -> sync -- : **200** : ""settings""
  sync -> sync : update //settings.json//
end

group Fetch common data
  sync -> gn ++ : **GET** : ""/observers""
  gn -> sync -- : **200** : ""[observer]""
  sync -> sync : update //observer// table
  sync -> gn ++ : **GET** : ""/taxa""
  gn -> sync -- : **200** : ""[taxon]""
  sync -> sync : update //taxon// table
end

...

group Fetch data for each module

  sync -> sync: fetch registered modules
  note left : read from\n""settings.json""

  loop for each registered module
    sync -> gn ++ : **GET** : ""/module/sync""
    gn -> sync -- : **200** : ""settings""
    sync -> sync : update //module/settings.json//
    sync -> sync : read registered endpoints

    loop for each registered endpoint
      sync -> gn ++ : **GET** : ""/module/xxx""
      gn -> sync -- : **200** : ""[xxx]""
      sync -> sync : update //xxx// table
    end

  end

end

deactivate sync
....

== Synchronize local inputs

[plantuml, images/sync_input, svg]
....
participant "mobile/sync" as sync << mobile >>
participant "GeoNature" as gn

activate sync

group Fetch exported inputs for each module

  sync -> sync: fetch registered modules
  note left : read from\n""settings.json""

  loop for each registered module
    sync -> sync : read exported inputs matching module

    loop for each input
      sync -> gn ++ : **POST** : ""/module/releve""
      note left
        **input:**
        {
          "id": <generated_id>,
          "module": <module>,
          ...
        }
      end note
      gn -> sync -- : **201**
      sync -> sync : delete input
    end

  end

end

deactivate sync
....