= Synchronization workflow

== Check for update

[plantuml,images/uml/sync_update,svg]
....
participant "mobile/sync" as sync << mobile >>
participant "GeoNature" as gn

activate sync

group Fetch common configuration data
    sync -> gn ++ : **GET** ""/api/gn_commons/t_mobile_apps""
    gn -> sync -- : **200**: ""[AppPackage]""
    note left
        **""AppPackage"":**
        {
            "url_apk": <URL>,
            "package": <application ID>,
            "app_code": <application code>,
            "version_code": <number>
        }
    end note
end

group Check for update
  sync -> sync : update //settings_sync.json//

  alt A new version is available
    sync -> sync : notify if we want to upgrade
  end
end
....

== Authentication

[plantuml,images/uml/sync_auth,svg]
....
participant "mobile/sync" as sync << mobile >>
participant "GeoNature" as gn

activate sync

group Check for login
    sync -> sync : Set login and password
    sync -> gn ++ : **POST** ""/api/auth/login""
    gn -> sync -- : **200**: ""AuthLogin""
    note left
        **""AuthLogin"":**
        {
            "user": {
                "id_application": <number>,
                "id_organisme": <number>,
                "identifiant": <user login>
            },
            "expires": <Date>
        }
    end note
    sync -> sync : Set cookie
end
....

== Update local database

[plantuml,images/uml/sync_data,svg]
....
participant "mobile/sync" as sync << mobile >>
participant "GeoNature" as gn

activate sync

ref over sync, gn : Check for login

group Fetch GeoNature data

    group Dataset
        sync -> gn ++ : **GET** ""/api/meta/datasets""
        gn -> sync -- : **200**: ""[Dataset]""
        note right of sync
            **""Dataset"":**
            {
                "id_dataset": <dataset ID>,
                "dataset_name": <name>,
                "dataset_desc": <description>,
                "active": <Boolean>,
                "meta_create_date": <Date>,
                "modules": {
                        "module_path": <String>
                }[]
            }
        end note
        sync -> sync : update //dataset// table
    end

    group Observers
        sync -> gn ++ : **GET** ""/api/users/menu/:observers_list_id""
        note right of sync
            ""observers_list_id"" from settings
        end note
        gn -> sync -- : **200**: ""[User]""
        note right of sync
            **""User"":**
            {
                "id_role": <user ID>,
                "nom_role": <lastname>,
                "prenom_role": <firstnane>
            }
        end note
        sync -> sync : update //observers// table
    end

    group Taxonomy
        sync -> gn ++ : **GET** ""/api/taxref/regnewithgroupe2""
        gn -> sync -- : **200**: ""[Taxonomy]""
        note right of sync
            **""Taxonomy"":**
            {
                <kingdom>: <group>[]
            }
        end note
        sync -> sync : update //taxonomy// table
    end

    group Taxa
        loop while response is not empty\nand response size matches ""page_size"" from settings
            sync -> gn ++ : **GET** ""/api/taxref/allnamebylist/:taxa_list_id""
            note right of sync
                ""taxa_list_id"" from settings
            end note
            gn -> sync -- : **200**: ""[Taxref]""
            note right of sync
                **""Taxref"":**
                {
                    "cd_nom": <taxon ID>,
                    "lb_nom": <name>,
                    "nom_vern": <common name>,
                    "nom_valide": <full name>,
                    "regne": <kingdom>,
                    "group2_inpn": <group>,
                    "search_name": <String>
                }
            end note
            sync -> sync : update //taxa// table
        end
        loop while response is not empty\nand response size matches ""page_size"" from settings
            sync -> gn ++ : **GET** ""/api/synthese/color_taxon?:code_area_type""
             note right of sync
                ""code_area_type"" from settings
            end note
            gn -> sync -- : **200**: ""[TaxrefArea]""
            note right of sync
                **""TaxrefArea"":**
                {
                    "cd_nom": <taxon ID>,
                    "id_area": <area ID>,
                    "color": <String>,
                    "nb_obs": <number of observers>,
                    "last_date": <last updated at>
                }
            end note
            sync -> sync : update //taxa_area// table
        end
    end

    group Nomenclature
        sync -> gn ++ : **GET** ""/api/nomenclatures/nomenclatures/taxonomy""
        gn -> sync -- : **200**: ""[NomenclatureType]""
        note right of sync
            **""NomenclatureType"":**
            {
                "id_type": <nomenclature type ID>,
                "mnemonique": <mnemonic code>,
                "label_default": <default name>,
                "nomenclatures": {
                    "id_nomenclature": <nomenclature ID>,
                    "cd_nomenclature": <nomenclature code>,
                    "hierarchy": <String>,
                    "label_default": <default name>,
                    "taxref": {
                        "regne": <kingdom>,
                        "group2_inpn": <group>,
                    }[],
                }[],
            }
        end note
        note over sync #FFAA88 : **TODO:**\nfetch registered modules from GeoNature
        loop for each registered module
            sync -> gn ++ : **GET** ""/api/:module/defaultNomenclatures""
            gn -> sync -- : **200**: ""[DefaultNomenclature]""
            note right of sync
                **""DefaultNomenclature"":**
                {
                    <mnemonic code>: <nomenclature ID>
                }
            end note
        end
        sync -> sync : update //nomenclature_types//  table
        sync -> sync : update //nomenclatures// table
        sync -> sync : update //nomenclatures_taxonomy//  table
        sync -> sync : update //default_nomenclatures//  table
    end

end

....

== Synchronize local inputs

[plantuml,images/uml/sync_input,svg]
....
participant "mobile/sync" as sync << mobile >>
participant "GeoNature" as gn

activate sync

group Fetch exported inputs from installed app

    sync -> sync: fetch installed apps
    note left : from Android  ""PackageManager""

    loop for each app
        sync -> sync : read exported inputs

        loop for each input
            sync -> sync : get module name from input
            sync -> gn ++ : **POST** ""api/:module/releve""
            note left
                **""SyncInput"":**
                {
                    "packageInfo": <PackageInfo>,
                    "filePath": <Path>,
                    "module": <String>,
                    "payload": <Object>,
                }
            end note
            gn -> sync -- : **200**
            sync -> sync : delete input file
        end
    end
end

....